/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ecotrackapp;

/**
 *
 * @author sohei
 */
public class EnergyCalculatorGUI extends javax.swing.JFrame {

 
    
    /**
     * Creates new form EnergyCalculatorGUI
     */
    
    public EnergyCalculatorGUI() {
        initComponents();
        
    }
    HomeGUI homeGUI = new HomeGUI();
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        powerRatingInput = new javax.swing.JTextField();
        hoursUsedLabel = new javax.swing.JLabel();
        hoursUsedInput = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        addApplicationBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        homeSectionBtn = new javax.swing.JButton();
        surveySectionBtn = new javax.swing.JButton();
        appliNameInput = new javax.swing.JTextField();
        calculatorSectionBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        calculateMonthlyBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        electricRateLbl = new javax.swing.JLabel();
        electricRateTf = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(400, 200));
        setResizable(false);

        powerRatingInput.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 0), 3, true));
        powerRatingInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                powerRatingInputActionPerformed(evt);
            }
        });

        hoursUsedLabel.setBackground(new java.awt.Color(255, 255, 255));
        hoursUsedLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        hoursUsedLabel.setText("Hours Used Daily: (An estimate)");
        hoursUsedLabel.setOpaque(true);

        hoursUsedInput.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 0), 3, true));
        hoursUsedInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hoursUsedInputActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("EcoTrack Energy Usage Calculator");
        jLabel4.setOpaque(true);

        addApplicationBtn.setText("Add Application");
        addApplicationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addApplicationBtnActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel2.setText("Household Application Name:");
        jLabel2.setOpaque(true);

        homeSectionBtn.setBackground(new java.awt.Color(102, 255, 102));
        homeSectionBtn.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        homeSectionBtn.setText("HOME");
        homeSectionBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        homeSectionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeSectionBtnActionPerformed(evt);
            }
        });

        surveySectionBtn.setBackground(new java.awt.Color(102, 255, 102));
        surveySectionBtn.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        surveySectionBtn.setText("SURVEY");
        surveySectionBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        surveySectionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                surveySectionBtnActionPerformed(evt);
            }
        });

        appliNameInput.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 0), 3, true));
        appliNameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appliNameInputActionPerformed(evt);
            }
        });

        calculatorSectionBtn.setBackground(new java.awt.Color(102, 255, 102));
        calculatorSectionBtn.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        calculatorSectionBtn.setText("ENERGY CONSUMPTION CALCULATOR");
        calculatorSectionBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        calculatorSectionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculatorSectionBtnActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel3.setText("Power Rating of the Household Application(KW-killowatts):");
        jLabel3.setOpaque(true);

        calculateMonthlyBtn.setText("Calculate ");
        calculateMonthlyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateMonthlyBtnActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("After you have added all applications and  \nare happy with your entries, please \nenter the rate at which you are charged for\n you electricity and click calculate. If you do \nnot know the exact rate enter an estimate.");
        jTextArea1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153), null, null));
        jScrollPane1.setViewportView(jTextArea1);

        electricRateLbl.setBackground(new java.awt.Color(255, 255, 255));
        electricRateLbl.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        electricRateLbl.setText("Electricity Rate:(Euro/KWh)");
        electricRateLbl.setOpaque(true);

        electricRateTf.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 0), 3, true));
        electricRateTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                electricRateTfActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\sohei\\Desktop\\EcoTrackIcon2.png")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(powerRatingInput, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(appliNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(hoursUsedInput, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hoursUsedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(addApplicationBtn)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(electricRateTf, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(electricRateLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(calculateMonthlyBtn)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(homeSectionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(calculatorSectionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(surveySectionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(166, 166, 166))))
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(calculatorSectionBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                    .addComponent(homeSectionBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(surveySectionBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(appliNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel3))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(powerRatingInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hoursUsedLabel)
                    .addComponent(electricRateLbl))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hoursUsedInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(electricRateTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addApplicationBtn)
                    .addComponent(calculateMonthlyBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addApplicationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addApplicationBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addApplicationBtnActionPerformed

    private void hoursUsedInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hoursUsedInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hoursUsedInputActionPerformed

    private void powerRatingInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_powerRatingInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_powerRatingInputActionPerformed

    private void calculatorSectionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculatorSectionBtnActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_calculatorSectionBtnActionPerformed

    private void appliNameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appliNameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_appliNameInputActionPerformed

    private void surveySectionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_surveySectionBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_surveySectionBtnActionPerformed

    private void homeSectionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeSectionBtnActionPerformed
        // TODO add your handling code here:
        homeGUI.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_homeSectionBtnActionPerformed

    private void calculateMonthlyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateMonthlyBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calculateMonthlyBtnActionPerformed

    private void electricRateTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_electricRateTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_electricRateTfActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EnergyCalculatorGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addApplicationBtn;
    private javax.swing.JTextField appliNameInput;
    private javax.swing.JButton calculateMonthlyBtn;
    private javax.swing.JButton calculatorSectionBtn;
    private javax.swing.JLabel electricRateLbl;
    private javax.swing.JTextField electricRateTf;
    private javax.swing.JButton homeSectionBtn;
    private javax.swing.JTextField hoursUsedInput;
    private javax.swing.JLabel hoursUsedLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField powerRatingInput;
    private javax.swing.JButton surveySectionBtn;
    // End of variables declaration//GEN-END:variables
}
