/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ecotrackapp;

import javax.swing.JOptionPane;

/**
 *
 * @author Ross P
 */
public class ThisSurveyGUI extends javax.swing.JFrame {

    private final SurveyQuestions surveyQuestions = new SurveyQuestions(); // Create instance

    //declare array of objects
    Answers[] arr;
    //declare counter
    int count;
    private int submitCount;

    /**
     * Creates new form ThisSurveyGUI
     */
    public ThisSurveyGUI() {
        initComponents();
        OriginalQuestions originalQuestions = new OriginalQuestions();
        qs1Lbl.setText(originalQuestions.getQuestion4());
        qs2Lbl.setText(originalQuestions.getQuestion5());
        qs3Lbl.setText(originalQuestions.getQuestion6());

        //create array
        arr = new Answers[2];
        count = 0;
        submitCount = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        resetBtn = new javax.swing.JButton();
        submitBtn = new javax.swing.JButton();
        qs1Lbl = new javax.swing.JLabel();
        qs3Lbl = new javax.swing.JLabel();
        qs2Lbl = new javax.swing.JLabel();
        qs2Tf = new javax.swing.JTextField();
        qs3Tf = new javax.swing.JTextField();
        surveySectionBtn = new javax.swing.JButton();
        calculatorSectionBtn = new javax.swing.JButton();
        homeSectionBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        qs1Tf = new javax.swing.JTextField();
        displayBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EcoTrack");
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);

        resetBtn.setText("Reset");
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });

        submitBtn.setText("Submit");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        qs1Lbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        qs1Lbl.setText("Question one is here?");

        qs3Lbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        qs3Lbl.setText("Question three is here?");

        qs2Lbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        qs2Lbl.setText("Question two is here?");

        qs2Tf.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 255, 102), 3, true));
        qs2Tf.setOpaque(true);
        qs2Tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qs2TfActionPerformed(evt);
            }
        });

        qs3Tf.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 255, 102), 3, true));
        qs3Tf.setOpaque(true);
        qs3Tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qs3TfActionPerformed(evt);
            }
        });

        surveySectionBtn.setBackground(new java.awt.Color(102, 255, 102));
        surveySectionBtn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        surveySectionBtn.setText("SURVEY");
        surveySectionBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        surveySectionBtn.setOpaque(true);
        surveySectionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                surveySectionBtnActionPerformed(evt);
            }
        });

        calculatorSectionBtn.setBackground(new java.awt.Color(102, 255, 102));
        calculatorSectionBtn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        calculatorSectionBtn.setText("ENERGY CONSUMPTION CALCULATOR");
        calculatorSectionBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        calculatorSectionBtn.setOpaque(true);
        calculatorSectionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculatorSectionBtnActionPerformed(evt);
            }
        });

        homeSectionBtn.setBackground(new java.awt.Color(102, 255, 102));
        homeSectionBtn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        homeSectionBtn.setText("HOME");
        homeSectionBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        homeSectionBtn.setOpaque(true);
        homeSectionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeSectionBtnActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ecotrackapp/EcoTrackIcon (2).png"))); // NOI18N

        qs1Tf.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 255, 102), 3, true));
        qs1Tf.setOpaque(true);
        qs1Tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qs1TfActionPerformed(evt);
            }
        });

        displayBtn.setText("Display");
        displayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(homeSectionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(calculatorSectionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(surveySectionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(qs1Tf, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(qs3Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
                        .addComponent(qs2Lbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(qs2Tf, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(qs1Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(resetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(94, 94, 94)
                                .addComponent(submitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(displayBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(qs3Tf, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(125, 125, 125))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(homeSectionBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                    .addComponent(calculatorSectionBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(surveySectionBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(qs1Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(qs1Tf, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(qs2Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(qs2Tf, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(qs3Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(qs3Tf, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(displayBtn)
                    .addComponent(submitBtn)
                    .addComponent(resetBtn))
                .addGap(60, 60, 60))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void qs2TfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qs2TfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qs2TfActionPerformed

    private void qs3TfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qs3TfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qs3TfActionPerformed

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        // TODO add your handling code here:
        OriginalQuestions originalQuestions = new OriginalQuestions();
        qs1Lbl.setText(originalQuestions.getQuestion4());
        qs2Lbl.setText(originalQuestions.getQuestion5());
        qs3Lbl.setText(originalQuestions.getQuestion6());

    }//GEN-LAST:event_resetBtnActionPerformed

    private void surveySectionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_surveySectionBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_surveySectionBtnActionPerformed

    private void calculatorSectionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculatorSectionBtnActionPerformed
        // TODO add your handling code here:

        EnergyCalculatorGUI myCalc = new EnergyCalculatorGUI();
        myCalc.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_calculatorSectionBtnActionPerformed

    private void homeSectionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeSectionBtnActionPerformed
        // TODO add your handling code here:

        HomeGUI myHome = new HomeGUI();
        myHome.setVisible(true);
        this.dispose();


    }//GEN-LAST:event_homeSectionBtnActionPerformed

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        if (qs1Tf.getText().equals("")
                || qs2Tf.getText().equals("")) {

            // Show a warning message
            JOptionPane.showMessageDialog(null, "All questions must be answered before submission!", "Warning", javax.swing.JOptionPane.WARNING_MESSAGE);

            return; // Exit the method without submitting
        }
        if (submitCount >= 2) {
            // If submit button is pressed more than twicegive warning
            JOptionPane.showMessageDialog(null, "You can not submit more than once per question!", "Warning", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;

        }
        Answers a;
        a = new Answers();
        String answer1 = qs1Tf.getText();
        String answer2 = qs2Tf.getText();
        String answer3 = qs3Tf.getText();
        // Pfill ans objs with data from tfs
        a.setAnswer1(answer1);
        a.setAnswer2(answer2);
        a.setAnswer3(answer3);
        if (count < arr.length) {
            //add object to array
            arr[count] = a;
            count++;
            JOptionPane.showMessageDialog(null, "Survey response submitted successfully!");
        }
        // Clear text fields
        qs1Tf.setText("");
        qs2Tf.setText("");
        qs3Tf.setText("");
        //change the questions on the label
        qs1Lbl.setText(surveyQuestions.getQuestion1());
        qs2Lbl.setText(surveyQuestions.getQuestion2());
        qs3Lbl.setText(surveyQuestions.getQuestion3());
    }//GEN-LAST:event_submitBtnActionPerformed

    private void qs1TfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qs1TfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qs1TfActionPerformed

    private void displayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayBtnActionPerformed
        // TODO add your handling code here:

        for (int i = 0; i < arr.length; i = i + 1) {
            try {
                JOptionPane.showMessageDialog(null, "answer : " + arr[i].getAnswer1() + "\n answer : " + arr[i].getAnswer2() + "\n answer : " + arr[i].getAnswer3());
            } catch (Exception e) {
                System.out.println("Error:" + e);
            }
        }
        JOptionPane.showMessageDialog(null, "Thank you for taking our survey!");
    }//GEN-LAST:event_displayBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThisSurveyGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThisSurveyGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThisSurveyGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThisSurveyGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThisSurveyGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calculatorSectionBtn;
    private javax.swing.JButton displayBtn;
    private javax.swing.JButton homeSectionBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel qs1Lbl;
    private javax.swing.JTextField qs1Tf;
    private javax.swing.JLabel qs2Lbl;
    private javax.swing.JTextField qs2Tf;
    private javax.swing.JLabel qs3Lbl;
    private javax.swing.JTextField qs3Tf;
    private javax.swing.JButton resetBtn;
    private javax.swing.JButton submitBtn;
    private javax.swing.JButton surveySectionBtn;
    // End of variables declaration//GEN-END:variables
}
