/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ecotrackapp;

/**
 *
 * @author sohei
 */
public class UserGuideGUI extends javax.swing.JFrame {

    /**
     * Creates new form UserGuideGUI
     */
    public UserGuideGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        step2Lbl = new javax.swing.JLabel();
        step1Lbl = new javax.swing.JLabel();
        step3Lbl = new javax.swing.JLabel();
        step2_1Lbl = new javax.swing.JLabel();
        step5Lbl = new javax.swing.JLabel();
        step3_1Lbl = new javax.swing.JLabel();
        step4Lbl = new javax.swing.JLabel();
        step5_1Lbl = new javax.swing.JLabel();
        titleLbl = new javax.swing.JLabel();
        seperateTitleS = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setResizable(false);

        step2Lbl.setBackground(new java.awt.Color(204, 255, 204));
        step2Lbl.setText("2. To display all the appliances you have added, click on the \"Display Appliances Button \"");
        step2Lbl.setOpaque(true);

        step1Lbl.setBackground(new java.awt.Color(204, 255, 204));
        step1Lbl.setText("1. Put in an appliance's details then click add");
        step1Lbl.setOpaque(true);

        step3Lbl.setBackground(new java.awt.Color(204, 255, 204));
        step3Lbl.setText("3. To delete an appliance, click on the delete button and enter the name of the appliance  ");
        step3Lbl.setOpaque(true);

        step2_1Lbl.setBackground(new java.awt.Color(204, 255, 204));
        step2_1Lbl.setText("click on the \"Display Energy Consumption\" button.");
        step2_1Lbl.setOpaque(true);

        step5Lbl.setBackground(new java.awt.Color(204, 255, 204));
        step5Lbl.setText("5. After you have added all the appliances that you use, put the value at which you are ");
        step5Lbl.setOpaque(true);

        step3_1Lbl.setBackground(new java.awt.Color(204, 255, 204));
        step3_1Lbl.setText("you want to delete.");
        step3_1Lbl.setOpaque(true);

        step4Lbl.setBackground(new java.awt.Color(204, 255, 204));
        step4Lbl.setText("4. If you want to see you energy consumption based on the appliances you have entered so ");
        step4Lbl.setOpaque(true);

        step5_1Lbl.setBackground(new java.awt.Color(204, 255, 204));
        step5_1Lbl.setText("charged for electricity and click calculate.");
        step5_1Lbl.setOpaque(true);

        titleLbl.setBackground(new java.awt.Color(153, 255, 153));
        titleLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        titleLbl.setText("How to Use The Energy Consumption Calculator:");
        titleLbl.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(step5_1Lbl)
                            .addComponent(step5Lbl)
                            .addComponent(step4Lbl)
                            .addComponent(step2_1Lbl)
                            .addComponent(step2Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(step3Lbl)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(step3_1Lbl)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(step1Lbl)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addComponent(seperateTitleS, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(titleLbl)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(titleLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(seperateTitleS, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(step1Lbl)
                .addGap(18, 18, 18)
                .addComponent(step2Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(step2_1Lbl)
                .addGap(18, 18, 18)
                .addComponent(step3Lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(step3_1Lbl)
                .addGap(18, 18, 18)
                .addComponent(step4Lbl)
                .addGap(18, 18, 18)
                .addComponent(step5Lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(step5_1Lbl)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserGuideGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserGuideGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserGuideGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserGuideGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserGuideGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator seperateTitleS;
    private javax.swing.JLabel step1Lbl;
    private javax.swing.JLabel step2Lbl;
    private javax.swing.JLabel step2_1Lbl;
    private javax.swing.JLabel step3Lbl;
    private javax.swing.JLabel step3_1Lbl;
    private javax.swing.JLabel step4Lbl;
    private javax.swing.JLabel step5Lbl;
    private javax.swing.JLabel step5_1Lbl;
    private javax.swing.JLabel titleLbl;
    // End of variables declaration//GEN-END:variables
}
